"""Shared auth constants used by both service and oauth_service."""

DEFAULT_STAGES = ["Applied", "Phone Screen", "Onsite", "Offer", "Rejected"]
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_MORNING_BRIEF_ENABLED = True
DEFAULT_MORNING_BRIEF_HOUR = 8
DEFAULT_MORNING_BRIEF_EMAIL = True
DEFAULT_MORNING_BRIEF_IN_APP = True
DEFAULT_WEEKLY_DIGEST_ENABLED = False
MORNING_BRIEF_HOUR_MIN = 0
MORNING_BRIEF_HOUR_MAX = 23

DEFAULT_AUTOPILOT_ENABLED = False
DEFAULT_AUTOPILOT_MIN_MATCH_SCORE = 80
DEFAULT_AUTOPILOT_MAX_DAILY = 5
AUTOPILOT_MIN_SCORE_MIN = 70
AUTOPILOT_MIN_SCORE_MAX = 95
AUTOPILOT_MAX_DAILY_MIN = 1
AUTOPILOT_MAX_DAILY_MAX = 10
