"""Shared auth constants used by both service and oauth_service."""

DEFAULT_STAGES = ["Applied", "Phone Screen", "Onsite", "Offer", "Rejected"]
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_MORNING_BRIEF_ENABLED = True
DEFAULT_MORNING_BRIEF_HOUR = 8
DEFAULT_MORNING_BRIEF_EMAIL = True
DEFAULT_MORNING_BRIEF_IN_APP = True
DEFAULT_WEEKLY_DIGEST_ENABLED = False
DEFAULT_WEEKLY_REVIEW_ENABLED = True
DEFAULT_WEEKLY_REVIEW_HOUR = 9
DEFAULT_WEEKLY_REVIEW_WEEKDAY = 0
MORNING_BRIEF_HOUR_MIN = 0
MORNING_BRIEF_HOUR_MAX = 23

DEFAULT_AUTOPILOT_ENABLED = False
DEFAULT_AUTOPILOT_MIN_MATCH_SCORE = 80
DEFAULT_AUTOPILOT_MAX_DAILY = 5
AUTOPILOT_MIN_SCORE_MIN = 70
AUTOPILOT_MIN_SCORE_MAX = 95
AUTOPILOT_MAX_DAILY_MIN = 1
AUTOPILOT_MAX_DAILY_MAX = 10
DEFAULT_GMAIL_INTERVIEW_PREP = True

DEFAULT_AGENT_COMMUNICATION_STYLE = "balanced"
AGENT_COMMUNICATION_STYLES = frozenset({"concise", "balanced", "detailed"})
AGENT_TARGET_ROLES_MAX = 10
AGENT_TARGET_ROLE_MAX_LENGTH = 80
AGENT_PREFERRED_LOCATIONS_MAX = 10
AGENT_LOCATION_MAX_LENGTH = 80
AGENT_CAREER_GOALS_MAX_LENGTH = 1000
AGENT_MEMORY_NOTES_MAX_LENGTH = 2000

WATCHLIST_COMPANIES_MAX = 25
WATCHLIST_COMPANY_NAME_MAX_LENGTH = 100
WATCHLIST_CAREERS_URL_MAX_LENGTH = 500

ALLOWED_EMAIL_DOMAINS: frozenset[str] = frozenset({"stanford.edu"})


def is_email_domain_allowed(email: str) -> bool:
    """True if the email's domain is in the allow-list (case-insensitive)."""
    if "@" not in email:
        return False
    domain = email.rsplit("@", 1)[1].lower()
    return domain in ALLOWED_EMAIL_DOMAINS
