"""Autopilot module constants."""

PENDING_STATUS = "pending"
APPROVED_STATUS = "approved"
DISMISSED_STATUS = "dismissed"

AUTOPILOT_APPLICATION_STAGE = "To Apply"
AUTOPILOT_SCAN_HOUR_UTC = 5

DESCRIPTION_FETCH_TIMEOUT_SECONDS = 10.0
DESCRIPTION_SNIPPET_MAX_CHARS = 2000
HTML_TAG_RE = r"<[^>]+>"

MATCH_SCORE_TIMEOUT_SECONDS = 15.0
PREP_GENERATION_TIMEOUT_SECONDS = 20.0
PREP_GENERATION_MAX_TOKENS = 800
